services:
  app:
    image: shridh0r/whatomate:latest
    container_name: whatomate_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - whatomate
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads:rw
      - ./audio:/app/audio:rw
    command: ["server", "-migrate"]

  db:
    image: postgres:17-alpine
    container_name: whatomate_db
    restart: unless-stopped
    networks:
      - whatomate
    environment:
      POSTGRES_USER: ${WHATOMATE_DATABASE_USER:-whatomate}
      POSTGRES_PASSWORD: ${WHATOMATE_DATABASE_PASSWORD}
      POSTGRES_DB: ${WHATOMATE_DATABASE_NAME:-whatomate}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${WHATOMATE_DATABASE_NAME:-whatomate}", "-U", "${WHATOMATE_DATABASE_USER:-whatomate}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: whatomate_redis
    restart: unless-stopped
    networks:
      - whatomate
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data

networks:
  whatomate:

volumes:
  postgres-data:
  redis-data:
